type Operation {
  id: ID!
  body: String!
  amount: Float!
  date: Date!
  repeat: Boolean!
  goal: String
  category: ID!
  positive: Boolean!
}

type Query {
  userOperations: [Operation]!
}

type Mutation {
  addOperation: Operation!
  deleteOperation(operationId: ID!): String!
}
